name: win

on: [push, pull_request]

jobs:
  win:

    env:
      VERSION: 0.26.0

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Checkout tag
      if: ${{ env.VERSION != '0.0.0' }}
      run: git -C ${{github.workspace}}/src/snapcast/ checkout v${{ env.VERSION }}
    - name: Setup environment
      run: |
        echo "SHA=$(git -C ${{github.workspace}}/src/snapcast rev-parse HEAD)" >> $env:GITHUB_ENV
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        #path: ${VCPKG_INSTALLATION_ROOT}\installed
        path: c:\vcpkg\installed
        key: ${{ runner.os }}-dependencies
    - name: Get dependenciesenv
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: vcpkg.exe install libflac libvorbis soxr opus boost-asio --triplet x64-windows
    - name: cmake build
      run: |
        echo vcpkg installation root: $env:VCPKG_INSTALLATION_ROOT
        cmake -S src\snapcast -B build -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-windows" -DCMAKE_BUILD_TYPE="Release" -DREVISION="${{ env.SHA }}" -DWERROR=ON -DBUILD_TESTS=ON
    - name: cmake make
      run: cmake --build build --config Release --parallel 3 --verbose
    - name: installer
      run: |
        copy ${env:VCPKG_INSTALLATION_ROOT}\installed\x64-windows\bin\FLAC.dll src\snapcast\bin\Release\
        copy ${env:VCPKG_INSTALLATION_ROOT}\installed\x64-windows\bin\ogg.dll src\snapcast\bin\Release\
        copy ${env:VCPKG_INSTALLATION_ROOT}\installed\x64-windows\bin\opus.dll src\snapcast\bin\Release\
        copy ${env:VCPKG_INSTALLATION_ROOT}\installed\x64-windows\bin\vorbis.dll src\snapcast\bin\Release\
        copy ${env:VCPKG_INSTALLATION_ROOT}\installed\x64-windows\bin\soxr.dll src\snapcast\bin\Release\
        copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\v142\vc_redist.x64.exe" src\snapcast\bin\Release\
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: develop_snapshot_win64-${{env.SHA}}
        path: |
          src\snapcast\bin\Release\snapclient.exe
          src\snapcast\bin\Release\FLAC.dll
          src\snapcast\bin\Release\ogg.dll
          src\snapcast\bin\Release\opus.dll
          src\snapcast\bin\Release\vorbis.dll
          src\snapcast\bin\Release\soxr.dll
          src\snapcast\bin\Release\vc_redist.x64.exe
